[Tue May 15 16:38:59.042331 2018] [:error] [pid 3115] [client 220.134.123.84:49217] [2018-05-15 16:38:59,041] ERROR in app: Exception on /api_listlocation/ [GET]
[Tue May 15 16:38:59.042365 2018] [:error] [pid 3115] [client 220.134.123.84:49217] Traceback (most recent call last):
[Tue May 15 16:38:59.042369 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
[Tue May 15 16:38:59.042372 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     response = self.full_dispatch_request()
[Tue May 15 16:38:59.042377 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Tue May 15 16:38:59.042380 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     rv = self.handle_user_exception(e)
[Tue May 15 16:38:59.042383 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
[Tue May 15 16:38:59.042386 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     reraise(exc_type, exc_value, tb)
[Tue May 15 16:38:59.042389 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Tue May 15 16:38:59.042392 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     rv = self.dispatch_request()
[Tue May 15 16:38:59.042394 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
[Tue May 15 16:38:59.042397 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue May 15 16:38:59.042400 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/var/www/html/location/flaskapp.py", line 42, in listlocation
[Tue May 15 16:38:59.042403 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     return jsonify({'result':q})
[Tue May 15 16:38:59.042406 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/json/__init__.py", line 321, in jsonify
[Tue May 15 16:38:59.042409 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     dumps(data, indent=indent, separators=separators) + '\\n',
[Tue May 15 16:38:59.042412 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/json/__init__.py", line 179, in dumps
[Tue May 15 16:38:59.042415 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     rv = _json.dumps(obj, **kwargs)
[Tue May 15 16:38:59.042418 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
[Tue May 15 16:38:59.042420 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     sort_keys=sort_keys, **kw).encode(obj)
[Tue May 15 16:38:59.042423 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/encoder.py", line 209, in encode
[Tue May 15 16:38:59.042426 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     chunks = list(chunks)
[Tue May 15 16:38:59.042429 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/encoder.py", line 434, in _iterencode
[Tue May 15 16:38:59.042432 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     for chunk in _iterencode_dict(o, _current_indent_level):
[Tue May 15 16:38:59.042435 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
[Tue May 15 16:38:59.042438 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     for chunk in chunks:
[Tue May 15 16:38:59.042449 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/encoder.py", line 408, in _iterencode_dict
[Tue May 15 16:38:59.042452 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     for chunk in chunks:
[Tue May 15 16:38:59.042455 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/encoder.py", line 442, in _iterencode
[Tue May 15 16:38:59.042462 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     o = _default(o)
[Tue May 15 16:38:59.042466 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/site-packages/flask/json/__init__.py", line 81, in default
[Tue May 15 16:38:59.042469 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     return _json.JSONEncoder.default(self, o)
[Tue May 15 16:38:59.042472 2018] [:error] [pid 3115] [client 220.134.123.84:49217]   File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
[Tue May 15 16:38:59.042474 2018] [:error] [pid 3115] [client 220.134.123.84:49217]     raise TypeError(repr(o) + " is not JSON serializable")
[Tue May 15 16:38:59.042477 2018] [:error] [pid 3115] [client 220.134.123.84:49217] TypeError: ObjectId('5afa5e9a584b1273c998c072') is not JSON serializable
