[Tue Jun 26 15:47:31.901125 2018] [:error] [pid 18036] [client 220.134.123.84:52146] [2018-06-26 15:47:31,899] ERROR in app: Exception on /chk_rssi/ [GET]
[Tue Jun 26 15:47:31.901169 2018] [:error] [pid 18036] [client 220.134.123.84:52146] Traceback (most recent call last):
[Tue Jun 26 15:47:31.901174 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
[Tue Jun 26 15:47:31.901177 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     response = self.full_dispatch_request()
[Tue Jun 26 15:47:31.901181 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Tue Jun 26 15:47:31.901185 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     rv = self.handle_user_exception(e)
[Tue Jun 26 15:47:31.901188 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
[Tue Jun 26 15:47:31.901191 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     reraise(exc_type, exc_value, tb)
[Tue Jun 26 15:47:31.901194 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Tue Jun 26 15:47:31.901197 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     rv = self.dispatch_request()
[Tue Jun 26 15:47:31.901201 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
[Tue Jun 26 15:47:31.901204 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 26 15:47:31.901207 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/var/www/html/location/flaskapp.py", line 160, in chk_rssi
[Tue Jun 26 15:47:31.901210 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     return render_template('chk_rssi.html')
[Tue Jun 26 15:47:31.901214 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 134, in render_template
[Tue Jun 26 15:47:31.901217 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
[Tue Jun 26 15:47:31.901220 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
[Tue Jun 26 15:47:31.901223 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     return self.get_template(template_name_or_list, parent, globals)
[Tue Jun 26 15:47:31.901227 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
[Tue Jun 26 15:47:31.901230 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     return self._load_template(name, self.make_globals(globals))
[Tue Jun 26 15:47:31.901233 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
[Tue Jun 26 15:47:31.901236 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     template = self.loader.load(self, name, globals)
[Tue Jun 26 15:47:31.901239 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
[Tue Jun 26 15:47:31.901243 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     code = environment.compile(source, name, filename)
[Tue Jun 26 15:47:31.901246 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 591, in compile
[Tue Jun 26 15:47:31.901249 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     self.handle_exception(exc_info, source_hint=source_hint)
[Tue Jun 26 15:47:31.901252 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
[Tue Jun 26 15:47:31.901259 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     reraise(exc_type, exc_value, tb)
[Tue Jun 26 15:47:31.901262 2018] [:error] [pid 18036] [client 220.134.123.84:52146]   File "/var/www/html/location/templates/chk_rssi.html", line 5, in template
[Tue Jun 26 15:47:31.901266 2018] [:error] [pid 18036] [client 220.134.123.84:52146]     {% endblock %}
[Tue Jun 26 15:47:31.901269 2018] [:error] [pid 18036] [client 220.134.123.84:52146] TemplateSyntaxError: Encountered unknown tag 'endblock'.
[Tue Jun 26 15:49:10.715157 2018] [:error] [pid 18233] [client 220.134.123.84:52609] [2018-06-26 15:49:10,714] ERROR in app: Exception on /chk_rssi/ [GET]
[Tue Jun 26 15:49:10.715188 2018] [:error] [pid 18233] [client 220.134.123.84:52609] Traceback (most recent call last):
[Tue Jun 26 15:49:10.715192 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
[Tue Jun 26 15:49:10.715196 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     response = self.full_dispatch_request()
[Tue Jun 26 15:49:10.715199 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Tue Jun 26 15:49:10.715202 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     rv = self.handle_user_exception(e)
[Tue Jun 26 15:49:10.715205 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
[Tue Jun 26 15:49:10.715209 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     reraise(exc_type, exc_value, tb)
[Tue Jun 26 15:49:10.715212 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Tue Jun 26 15:49:10.715215 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     rv = self.dispatch_request()
[Tue Jun 26 15:49:10.715218 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
[Tue Jun 26 15:49:10.715221 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Jun 26 15:49:10.715224 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/var/www/html/location/flaskapp.py", line 160, in chk_rssi
[Tue Jun 26 15:49:10.715227 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     return render_template('chk_rssi.html')
[Tue Jun 26 15:49:10.715229 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 135, in render_template
[Tue Jun 26 15:49:10.715233 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     context, ctx.app)
[Tue Jun 26 15:49:10.715235 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 117, in _render
[Tue Jun 26 15:49:10.715238 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     rv = template.render(context)
[Tue Jun 26 15:49:10.715241 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
[Tue Jun 26 15:49:10.715244 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     return self.environment.handle_exception(exc_info, True)
[Tue Jun 26 15:49:10.715247 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
[Tue Jun 26 15:49:10.715250 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     reraise(exc_type, exc_value, tb)
[Tue Jun 26 15:49:10.715253 2018] [:error] [pid 18233] [client 220.134.123.84:52609]   File "/var/www/html/location/templates/base.html", line 7, in template
[Tue Jun 26 15:49:10.715256 2018] [:error] [pid 18233] [client 220.134.123.84:52609]     <title>(% block title %)  {% endblock %}</title>
[Tue Jun 26 15:49:10.715267 2018] [:error] [pid 18233] [client 220.134.123.84:52609] TemplateSyntaxError: Encountered unknown tag 'endblock'.
<<<<<<< HEAD
[Wed Jun 27 12:01:42.178336 2018] [:error] [pid 18364] [client 27.52.160.132:32741] [2018-06-27 12:01:42,143] ERROR in app: Exception on /do_learm/ [GET]
[Wed Jun 27 12:01:42.178367 2018] [:error] [pid 18364] [client 27.52.160.132:32741] Traceback (most recent call last):
[Wed Jun 27 12:01:42.178372 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
[Wed Jun 27 12:01:42.178375 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     response = self.full_dispatch_request()
[Wed Jun 27 12:01:42.178379 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
[Wed Jun 27 12:01:42.178382 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     rv = self.handle_user_exception(e)
[Wed Jun 27 12:01:42.178385 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
[Wed Jun 27 12:01:42.178389 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     reraise(exc_type, exc_value, tb)
[Wed Jun 27 12:01:42.178392 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Wed Jun 27 12:01:42.178395 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     rv = self.dispatch_request()
[Wed Jun 27 12:01:42.178398 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
[Wed Jun 27 12:01:42.178401 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jun 27 12:01:42.178404 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/var/www/html/location/flaskapp.py", line 39, in do_learm
[Wed Jun 27 12:01:42.178407 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     X_train, X_test, y_train, y_test = train_test_split(dataframe[data_list], dataframe[['block']], test_size=0.3)
[Wed Jun 27 12:01:42.178410 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 2679, in __getitem__
[Wed Jun 27 12:01:42.178413 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     return self._getitem_array(key)
[Wed Jun 27 12:01:42.178416 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/pandas/core/frame.py", line 2723, in _getitem_array
[Wed Jun 27 12:01:42.178419 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     indexer = self.loc._convert_to_indexer(key, axis=1)
[Wed Jun 27 12:01:42.178422 2018] [:error] [pid 18364] [client 27.52.160.132:32741]   File "/usr/lib64/python2.7/site-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
[Wed Jun 27 12:01:42.178425 2018] [:error] [pid 18364] [client 27.52.160.132:32741]     .format(mask=objarr[mask]))
[Wed Jun 27 12:01:42.178428 2018] [:error] [pid 18364] [client 27.52.160.132:32741] KeyError: "[u'F5B5002B888C' u'35A9002B888C'] not in index"
[Wed Jun 27 13:11:00.801174 2018] [:error] [pid 18364] [client 1.200.39.200:27236] [2018-06-27 13:11:00,800] ERROR in app: Exception on /chk_rssi/ [POST], referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801209 2018] [:error] [pid 18364] [client 1.200.39.200:27236] Traceback (most recent call last):, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801213 2018] [:error] [pid 18364] [client 1.200.39.200:27236]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801217 2018] [:error] [pid 18364] [client 1.200.39.200:27236]     response = self.full_dispatch_request(), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801233 2018] [:error] [pid 18364] [client 1.200.39.200:27236]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801236 2018] [:error] [pid 18364] [client 1.200.39.200:27236]     rv = self.handle_user_exception(e), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801239 2018] [:error] [pid 18364] [client 1.200.39.200:27236]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801242 2018] [:error] [pid 18364] [client 1.200.39.200:27236]     reraise(exc_type, exc_value, tb), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801244 2018] [:error] [pid 18364] [client 1.200.39.200:27236]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801247 2018] [:error] [pid 18364] [client 1.200.39.200:27236]     rv = self.dispatch_request(), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801250 2018] [:error] [pid 18364] [client 1.200.39.200:27236]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801253 2018] [:error] [pid 18364] [client 1.200.39.200:27236]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801255 2018] [:error] [pid 18364] [client 1.200.39.200:27236]   File "/var/www/html/location/flaskapp.py", line 156, in chk_rssi, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801258 2018] [:error] [pid 18364] [client 1.200.39.200:27236]     rssi = d[detector_id], referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:11:00.801261 2018] [:error] [pid 18364] [client 1.200.39.200:27236] KeyError: u'35A9002B888C', referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219639 2018] [:error] [pid 19980] [client 1.200.39.200:27840] [2018-06-27 13:15:05,218] ERROR in app: Exception on /chk_rssi/ [POST], referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219669 2018] [:error] [pid 19980] [client 1.200.39.200:27840] Traceback (most recent call last):, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219674 2018] [:error] [pid 19980] [client 1.200.39.200:27840]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219677 2018] [:error] [pid 19980] [client 1.200.39.200:27840]     response = self.full_dispatch_request(), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219681 2018] [:error] [pid 19980] [client 1.200.39.200:27840]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219684 2018] [:error] [pid 19980] [client 1.200.39.200:27840]     rv = self.handle_user_exception(e), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219687 2018] [:error] [pid 19980] [client 1.200.39.200:27840]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219690 2018] [:error] [pid 19980] [client 1.200.39.200:27840]     reraise(exc_type, exc_value, tb), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219693 2018] [:error] [pid 19980] [client 1.200.39.200:27840]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219696 2018] [:error] [pid 19980] [client 1.200.39.200:27840]     rv = self.dispatch_request(), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219707 2018] [:error] [pid 19980] [client 1.200.39.200:27840]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219710 2018] [:error] [pid 19980] [client 1.200.39.200:27840]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219713 2018] [:error] [pid 19980] [client 1.200.39.200:27840]   File "/var/www/html/location/flaskapp.py", line 156, in chk_rssi, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219716 2018] [:error] [pid 19980] [client 1.200.39.200:27840]     rssi = d[detector_id], referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:05.219718 2018] [:error] [pid 19980] [client 1.200.39.200:27840] KeyError: u'35A9002B888C', referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579073 2018] [:error] [pid 20009] [client 1.200.39.200:27394] [2018-06-27 13:15:10,578] ERROR in app: Exception on /chk_rssi/ [POST], referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579101 2018] [:error] [pid 20009] [client 1.200.39.200:27394] Traceback (most recent call last):, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579105 2018] [:error] [pid 20009] [client 1.200.39.200:27394]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579108 2018] [:error] [pid 20009] [client 1.200.39.200:27394]     response = self.full_dispatch_request(), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579112 2018] [:error] [pid 20009] [client 1.200.39.200:27394]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579115 2018] [:error] [pid 20009] [client 1.200.39.200:27394]     rv = self.handle_user_exception(e), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579118 2018] [:error] [pid 20009] [client 1.200.39.200:27394]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579120 2018] [:error] [pid 20009] [client 1.200.39.200:27394]     reraise(exc_type, exc_value, tb), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579123 2018] [:error] [pid 20009] [client 1.200.39.200:27394]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579126 2018] [:error] [pid 20009] [client 1.200.39.200:27394]     rv = self.dispatch_request(), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579128 2018] [:error] [pid 20009] [client 1.200.39.200:27394]   File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579131 2018] [:error] [pid 20009] [client 1.200.39.200:27394]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579134 2018] [:error] [pid 20009] [client 1.200.39.200:27394]   File "/var/www/html/location/flaskapp.py", line 156, in chk_rssi, referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579136 2018] [:error] [pid 20009] [client 1.200.39.200:27394]     rssi = d[detector_id], referer: http://location.ladesign.tw/chk_rssi/
[Wed Jun 27 13:15:10.579139 2018] [:error] [pid 20009] [client 1.200.39.200:27394] KeyError: u'35A9002B888C', referer: http://location.ladesign.tw/chk_rssi/
=======
>>>>>>> 6547440b7a6d378df146d5ae9bfeb829aa9c25b2
